### ISSUE TITLE
Search dosnt appear to correctly work

### ISSUE THREAD

**Issue by molster** [webextensions/live-css-editor#142] opened 2024-07-19 17:56 UTC
I didnt see anything in the documentation for this, so was jsut using CTRL F (both in browser, and when popped out as its own window)

However CTRL F only searches for content that is in the view. If i have about 900+ lines, you basically cant search any of the css.

**Comment by webextensions** [comment] 2024-07-19 21:43
@molster 
Thank you for your report.

We use the CodeMirror library for rendering the code editor functionality. By default, for performance reasons, it does lazy rendering which is controlled by a parameter called `viewportMargin` (https://codemirror.net/5/doc/manual.html#option_viewportMargin).

The default value for `viewportMargin` is 10. If we set it to a very high number (or Infinity), then that would solve the search issue for high number of lines of code.

We will attempt the change in the following ways:
* Phase 1: We update the extension by setting the `viewportMargin` to 5000 by default assuming that it should work well enough for most of the use cases without causing a major performance hit.
* Phase 1 follow up: We wait for sometime so that we don't get any reports of performance issue from the users.
* Phase 2: Provide a customization option for this under the `More options` page where the user should be able to choose an appropriate value as per their needs.

**Comment by webextensions** [comment] 2024-07-19 22:06
We hope that the root cause should be fixed for most of the use-cases as per the above mentioned **Phase 1** changes.

Keeping the issue open for the updates to be done for **Phase 2**.

**Comment by molster** [comment] 2024-07-20 00:06
Thank you! This will be such a time saver.

**Comment by webextensions** [comment] 2024-07-28 09:26
Added a TODO note for the remaining part (https://github.com/webextensions/live-css-editor/commit/f2d3df6709ec8bd6662bbb58a6bc89a4c4377975) and closing this issue.

**Closed by webextensions** 2024-07-28 09:26 UTC
