### ISSUE TITLE
sass parser uses scss instead of sass

### ISSUE THREAD

**Issue by spearmootz** [webextensions/live-css-editor#68] opened 2021-07-23 16:51 UTC
there is a syntax difference, particularly the brackets.  i thought the plugin was broken because it said that my selector had an error but in reality it was working correctly.  it would be awesome to be able to use both sass and scss but at the very least scss should be labeled properly.

its great work though

**Comment by webextensions** [comment] 2021-07-23 19:51
@spearmootz

The current version of `sass.js` which is being used is the one from https://github.com/medialize/sass.js / https://www.npmjs.com/package/sass.js / https://cdnjs.cloudflare.com/ajax/libs/sass.js/0.11.1/sass.sync.min.js which was last updated around 2 years ago (derived from https://github.com/sass/libsass v3.6.2).

For future, the plan is to move to https://www.npmjs.com/package/sass , hopefully the migration/upgrade would work out with similar capabilities. When that would happen, that is not planned yet.

Due to lack of details in the issue, probably it is safe to assume that the syntax difference is happening because of the outdated Sass.

Closing the issue on the basis of the above mentioned assumptions and plan.

**Comment by spearmootz** [comment] 2021-07-23 19:55
I don't think it is because of outdated syntax. Here is what I tried (typed it in phone in case spacing is wrong)

body
    div
        background-color: blue

**Comment by webextensions** [comment] 2021-07-23 20:21
@spearmootz 
Right, my bad.

So, the issue is basically about fixing the confusion about the "SCSS" vs "Sass" syntax.

Since the term "Sass" is used polymorphically (assuming this is a valid word in this context), it can be confusing for developers. Also, using the term "SCSS" might be slightly confusing for some of the beginner developers. But still, changing the language/syntax mode to say "scss" might be the most correct option in this case.

But, before renaming the language/syntax mode, we will verify if the https://www.npmjs.com/package/sass supports both the syntaxes (it may still take weeks/months before we go ahead with the upgrade/migration). If that turns out to be the case, then that wouldn't need the above mentioned changes.

Reopening.

**Comment by spearmootz** [comment] 2021-07-23 20:27
The syntax is old and is probably supported. Probably a flag needs to be passed if it's SASS.

I'm not in any rush, i resorted to watching and building to a folder and adding it to chrome override feature.

**Comment by chrisspiegl** [comment] 2021-11-12 09:32
I just found the same. Maybe in a future version it'd be good to just add sass and scss to the top bar to choose from? So that we can chose if we want to write braces and such?

**Closed** 2022-06-04 13:32 UTC

**Comment by webextensions** [comment] 2022-06-04 13:47
Added support for `Sass` syntax as an alternative to the `SCSS` syntax.

**This feature would be available v8.18.2 onwards.**

**Note:**
To enable the feature, one would need to go to the `Extension options` (`Triple dot menu` > `More options`) and enable it under `Experimental options`.

**Why is it added under `Experimental options` ?**
1. The error reporting (via the library) for `Sass` syntax is not ideal
2. The `Sass` syntax is farther from web standards compared to `SCSS` syntax
