### ISSUE TITLE
Not working on private network

### ISSUE THREAD

**Issue by DesignseedNZ** [webextensions/live-css-editor#16] opened 2018-07-16 04:13 UTC
I have installed this extension on a browser within a private network (no connection to the internet). It is not working.  Should I expect it to work?  Does it require internet access?  (I have installed it successfully on a public network).  Thanks.

**Comment by webextensions** [comment] 2018-08-04 19:31
Closing as "Incomplete" due to lack of steps to reproduce.

**Closed by webextensions** 2018-08-04 19:31 UTC
